const shopActionTypes = {
    FETCH_COLLECTIONS_PENDING : 'FETCH_COLLECTIONS_PENDING',
    FETCH_COLLECTIONS_SUCCESS : 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILED : 'FETCH_COLLECTIONS_FAILED'


}
export default shopActionTypes